title: Swiss Jekyll Theme
description: Jem Richards Books
social_link: facebook
social_username: Jem Richards
github_repo: Jem Richards
github_username: Jem Richards
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /jemrichardsbooks_com
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
